### ISSUE TITLE
Clicking on alert opens TONS of new tabs

### ISSUE THREAD

**Issue by jonasgrilleres** [Frenchcooc/kima#1]
I have noticed since a couple of weeks that when I click on a new investment alert, it opens a lot of new tabs (10+) to the company's website.

**Comment by Frenchcooc** [comment]
Hi Jonas! Thanks for reporting this bug. I'm looking at it and will get back to you soon. Sorry for that.

**Comment by cuireuncroco** [comment]
@jonasgrilleres thanks for reporting, I've had the same issue this morning, clicking on notification opened 4 tabs. We are reviewing the issue. Let us know if the problem comes back.

**Comment by Frenchcooc** [comment]
@jonasgrilleres a new version has been released last week to fix that clicking issue. So I'm closing the issue right now, but let me know if it appears again (hopefully not!).
